version: '3.8'

services:
  reservations:
      build:
        context: .
        dockerfile: ./apps/reservations/Dockerfile
        target: ${NODE_ENV}
      container_name: reservations-service
      command: npm run start:dev reservations
      ports:
        - ${RESERVATIONS_PORT}:${RESERVATIONS_PORT}
      depends_on:
       - reservations-mongo
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  auth:
      build:
        context: .
        dockerfile: ./apps/auth/Dockerfile
        target: ${NODE_ENV}
      container_name: auth-service
      command: npm run start:dev auth
      ports:
        - 3001:3001
      depends_on:
       - auth-mongo  
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always     

  reservations-mongo:
    image: mongo
    container_name: reservations-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/var/lib/reservations/data
    restart: always

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/var/lib/auth/data
    restart: always

volumes:
  mongodb_data:
