version: '3.8'

services:
  booking-service:
      build:
        context: .
        dockerfile: ./apps/booking/Dockerfile
        target: ${NODE_ENV}
      container_name: booking-service
      command: npm run start:debug booking
      depends_on:
        - booking-postgres
      env_file:
        - ./apps/booking/.env
      ports:
        # - ${BOOKING_PORT}:${BOOKING_PORT}
        - 9229:9229
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  auth-service:
      build:
        context: .
        dockerfile: ./apps/auth/Dockerfile
        target: ${NODE_ENV}
      container_name: auth-service
      command: npm run start:debug auth
      depends_on:
        - auth-mongo
      env_file:
        - ./apps/auth/.env
      # ports:
        # - ${AUTH_PORT}:${AUTH_PORT}
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  payments-service:
      build:
        context: .
        dockerfile: ./apps/payments/Dockerfile
        target: ${NODE_ENV}
      container_name: payments-service
      command: npm run start:dev payments
      env_file:
        - ./apps/payments/.env
      # ports:
        # - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  notifications-service:
      build:
        context: .
        dockerfile: ./apps/notifications/Dockerfile
        target: ${NODE_ENV}
      container_name: notifications-service
      command: npm run start:dev notifications
      env_file:
        - ./apps/notifications/.env
      # ports:
        # - ${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT} 
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/var/lib/auth/data
    restart: always    

  booking-postgres:
    image: postgres
    container_name: booking-postgres
    environment:
      - POSTGRES_DB=${BOOKING_DB_NAME}
      - POSTGRES_USER=${BOOKING_DB_USER}
      - POSTGRES_PASSWORD=${BOOKING_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/booking/data
    ports:
      - 5432:5432
    restart: always  

  nginx-gateway:
    image: nginx
    container_name: nginx-gateway
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - booking-service
      - auth-service 

volumes:
  mongodb_data:
  postgres_data:

