version: '3.8'

services:
  reservations:
      build:
        context: .
        dockerfile: ./apps/reservations/Dockerfile
        target: ${NODE_ENV}
      container_name: reservations-service
      command: npm run start:dev reservations
      depends_on:
        - reservations-mongo
      env_file:
        - ./apps/reservations/.env
      ports:
        - ${RESERVATIONS_PORT}:${RESERVATIONS_PORT}
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  auth:
      build:
        context: .
        dockerfile: ./apps/auth/Dockerfile
        target: ${NODE_ENV}
      container_name: auth-service
      command: npm run start:dev auth
      depends_on:
        - auth-mongo
      env_file:
        - ./apps/auth/.env
      ports:
        - ${AUTH_PORT}:${AUTH_PORT} 
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  payments:
      build:
        context: .
        dockerfile: ./apps/payments/Dockerfile
        target: ${NODE_ENV}
      container_name: payments-service
      command: npm run start:dev payments
      env_file:
        - ./apps/payments/.env
      ports:
        - ${PAYMENTS_PORT}:${PAYMENTS_PORT} 
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  notifications:
      build:
        context: .
        dockerfile: ./apps/notifications/Dockerfile
        target: ${NODE_ENV}
      container_name: notifications-service
      command: npm run start:dev notifications
      env_file:
        - ./apps/notifications/.env
      ports:
        - ${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT} 
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: always

  reservations-mongo:
    image: mongo
    container_name: reservations-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/var/lib/reservations/data
    restart: always

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/var/lib/auth/data
    restart: always

volumes:
  mongodb_data:
